### ISSUE TITLE
npm install is blocked by npm-init-generator

### ISSUE THREAD

**Issue by akougblenou** [caseyWebb/generator-npm-init#113]
Hi, I am running into an issue that I have a hard time to get around.

I am new to Yeoman and came across this generator and thought it would help me speed-up the implementation of my generator  by allowing me to performing the npm init.
That part works just fine, but when I try to write into the package.json in order to install my dependencies, that part just does not work.

I have transformed it as a sub-generator but still no chance there.
Both code work fine seperately but not together. What am I missing, is what I am trying to do impossible ? 
Do I need to create a npm init of my own ? 

here is a (non-exhaustive) snippet of my code:
in app/index.js
```javascript
const yosay = require("yosay");
const pckOptions = {
  // skip prompts
  'skip-name': false,
  'skip-description': false,
  'skip-version': false,
  'skip-main': false,
  'skip-test': false,
  'skip-repo': false,
  'skip-keywords': false,
  'skip-author': false,
  'skip-license': false,
  // supply alternative defaults
  name: '<%= destFolderName %>',
  version: '0.0.0',
  description: '',
  main: 'index.js',
  test: 'echo "Error: no test specified" && exit 1',
  repo: '',
  keywords: [],
  author: '',
  license: 'ISC',

  // configure run script defaults
  scripts: {
    // some commands goes here
  }
};

module.exports = class extends Generator {
  initializing() {
    this.composeWith(require.resolve("../install-packages"));
    this.composeWith(require.resolve("generator-npm-init/app"), pckOptions);
  }

  prompting() {
    // Have Yeoman greet the user.
    this.log(
      yosay(
        `Welcome to the well-made ${chalk.blue(
          "generator-new-generator"
        )} generator!`
      )
    );
  }  
};
```

in install-packages/index.js
```javascript

const Generator = require("yeoman-generator");

const pkgJson = {
  devDependencies: {
    // all my dev dependencies
},
  dependencies: {
    // all my dependencies
  }
};

module.exports = class extends Generator {
    writing() {
        this.fs.extendJSON(this.destinationPath("package.json"), pkgJson);
    }

  install() {
    this.npmInstall();
  }
};

```

**Comment by caseyWebb** [comment]
Have you played around with the order here?

```javascript
  initializing() {
    this.composeWith(require.resolve("../install-packages"));
    this.composeWith(require.resolve("generator-npm-init/app"), pckOptions);
  }
```

I'm not sure of the internals of yeoman, but I would try swapping those since your generator expects to extend the JSON. If that isn't a quick-fix I'll dig into this more to figure out how to do it.

**Comment by akougblenou** [comment]
I have played with the order, it wasn't that, I was using the wrong method to perform the instal, I'll post the answer here once I got time !!
Thanks for the help though !
