### ISSUE TITLE
Composition example in readme is not correct

### ISSUE THREAD

**Issue by Knorcedger** [caseyWebb/generator-npm-init#6]
The composition example you provide in your readme file is not correct. Something is missing i suppose.

P.S. Initially, I was trying to run `this.spawnCommandSync('npm', ['init']);` but it was causing conflicts with some other generators im using and the package.json was overwritten, and then I found your plugin. Do you know why it was causing those conflicts?

**Comment by caseyWebb** [comment]
Thanks for that, I assume you meant the `require('generator-npm-init/generators/app')` where it should have been `require('generator-npm-init/app')`.

Yeoman is weird re: how it deals w/ conflicts IME. It will make no attempt to merge changes w/ existing files. Does using this generator still cause conflicts? I would expect so, but I literally just started using Yeoman about a week ago, so I'm still fuzzy on how everything work exactly.

**Comment by Knorcedger** [comment]
Hey, not only the path, but that `: false,` at the end.

I'm also new with Yeoman, using it for a couple weeks now, and created a few generators. It generally handles conflicts well, for example, in my [knr-generator](https://github.com/Knorcedger/generator-knr-generator) which also uses your generator, there are other generators that modify the package.json, but everything ends up fine. Its just when i use `npm init` that it gets overwritten, and I'm not sure why.

Btw, your generator also creates a .yo-rc.json file, which I don't think it should, am I right?

**Comment by caseyWebb** [comment]
afaik using `this.config` is what writes the .yo-rc.json, which I'm using to initialize the defaults. If you look in it, it pretty much mirrors your package.json. I could probably implement another way, but it doesn't really seem to be a dealbreaker to me atm.

I'd wager a bet that yeoman is aware of which files it has created, and thus handles merges in them. When you use `this.spawnCommandSync()`, you're bypassing yeoman, therefore as far as it knows that `package.json` was there when you ran `yo`, in which yeoman opts to always ask the user to resolve conflicts.

**Comment by caseyWebb** [comment]
idk where my head was when I was writing that README.md...

**Comment by Knorcedger** [comment]
The readme seems fine now, and tnx for the awesome generator. 

The .yo-rc.json is not a problem, just a file I have to delete by hand :P
