### ISSUE TITLE
Small inconsistencies with npm init

### ISSUE THREAD

**Issue by Telokis** [caseyWebb/generator-npm-init#68]
Hey!

I just tried your generator to see how it matches the real `npm init` and noticed that there are two small name issues in the questions.

* ~npm asks for `package name` and you ask for `name`.~
* ~npm asks for `entry point` and you ask for `main point`.~

Moreover, `npm init` asks for confirmation before writting the file. (This should be optional)

In the two screenshots below, you can see a comparison of the two commands:

![image](https://user-images.githubusercontent.com/6382729/45513071-fbfbc900-b7a1-11e8-80b2-005236278c77.png)

![image](https://user-images.githubusercontent.com/6382729/45513080-028a4080-b7a2-11e8-8a08-2395c6c9b9ec.png)

~One last detail you can notice is that this generator writes `"force-install": false` inside the `package.json`  file.~

Thanks in advance for considering this issue.

**Comment by caseyWebb** [comment]
Changes published in [v1.5.0](https://github.com/caseyWebb/generator-npm-init/releases/tag/v1.5.0)
