### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by kevincam3** [caseyWebb/generator-npm-init#70]
I get the following error:
I have installed the module and it's located in the node folder.
Error: Cannot find module 'generator-npm-init/app'

**Comment by caseyWebb** [comment]
Can you give me some more info as to what you're trying to do, and/or some code?

If you're trying to use it globally, i.e. as `yo npm-init`, you need to ensure you're installing globally (`npm install -g generator-npm-init` or `yarn global add generator-npm-init`). If you're using with composition, I need some more context to help you out.

**Comment by caseyWebb** [comment]
I'm afraid I'm not really able to help much without a complete example; I tried making a minimal example with you code, but I've not used yeoman in a very long time and don't really remember how to use it to be completely honest with you.

If your generator isn't sensitive and you can push the entire repo to github, I'm more that willing to clone and help dig into it.

P.S. I've edited your post, but if you surround your code blocks with ` ```<language>`, they will be formatted as code. For example:

``````javascript
```javascript
console.log('hello, world!')
```
``````

**Comment by anoblet** [comment]
@kevincam3 `generator-npm-init` has to be a local dependency to the project. Run `npm i -D generator-npm-init`
